---
client_name:
  long: "Potos Linux Client"
  short: "potos"
disk_encryption:
  enable: false
  init_password: "install"
specs:
  url: "https://github.com/projectpotos/"
  repo: "ansible-specs-potos"
  branch: "main"
initial_hostname: "potoshostname01"
initial_user:
  username: "admin"
  password: "$6$L36BiUuVCSipvlO8$oGI0C.LXZegkbftFkVDXXaasTM6zs9LM71BkqZToKw5aOZ7Yr70pkzH3P9Xz5R.n0ULJ0Zf8v5ZQ/eH8flDR7/"
environment: "production"
first_boot_ansible:
  runtype: "setup"
full_unattended_install: false
input:
  iso_filename: "ubuntu-22.04.1-live-server-amd64.iso"
  iso_url: "https://releases.ubuntu.com/22.04/ubuntu-22.04.1-live-server-amd64.iso"
  iso_sha256_filename: "SHA256SUMS"
  iso_sha256_url: "https://releases.ubuntu.com/22.04/SHA256SUMS"
output:
  version: "22.04"
  iso_filename: "potos-installer.iso"
preinstall_packages:
  - python3-virtualenv
  - linux-generic-hwe-22.04
  - ubuntu-desktop
  - plymouth-theme-ubuntu-logo
  - ldap-utils
  - yad
